### ISSUE TITLE
scraper vytazil len 11 zaznamov, na zdrojovom webe ich je ale ovela viac

### ISSUE THREAD

**Issue by hanecak** [soit-sk/zmluvy_bratislava#1]
Pred zhruba rokom vytazil scraper zo zdrojoveho weby len 15 zaznamov a aktualne SQlite na Morph.io obsahuje len 11 poloziek. Pricom ale zdrojovy web obsahuje o dost viac poloziek.

Scraper teda este nie je hotovy.

**Comment by ricco386** [comment]
Zda sa ze scraper nevie pagovat na dalsiu stranku a parsuje iba prvu a potom skonci

**Comment by katkad** [comment]
ano, preto je na piratepade napisane
- nescrapuje vsetko; dokoncit
